// <auto-generated />
using System;
using GloomhavenCompanion.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GloomhavenCompanion.Infrastructure.Migrations
{
    [DbContext(typeof(GloomhavenCompanionDbContext))]
    [Migration("20241112103247_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.CampaignScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("ScenarioId");

                    b.ToTable("CampaignScenarios");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NeedShuffle")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsShowingBackCard")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsShuffled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Effect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "img/Elements/FirePicture.png",
                            Name = "Feu",
                            State = 0
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "img/Elements/DarknessPicture.png",
                            Name = "Ténèbre",
                            State = 0
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "img/Elements/EarthPicture.png",
                            Name = "Terre",
                            State = 0
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "img/Elements/WindPicture.png",
                            Name = "Vent",
                            State = 0
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "img/Elements/LightPicture.png",
                            Name = "Lumière",
                            State = 0
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "img/Elements/FrostPicture.png",
                            Name = "Givre",
                            State = 0
                        });
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeStarted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GameState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MonsterDeckId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonsterDeckId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("HealthPointsMax")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("DeckId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.PlayerGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("PlayerGame");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "img/Scenarios/gh-1.png",
                            Name = "Scenario 1"
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "img/Scenarios/gh-10.png",
                            Name = "Scenario 10"
                        },
                        new
                        {
                            Id = 11,
                            ImagePath = "img/Scenarios/gh-11-12.png",
                            Name = "Scenario 11"
                        },
                        new
                        {
                            Id = 12,
                            ImagePath = "img/Scenarios/gh-11-12.png",
                            Name = "Scenario 12"
                        },
                        new
                        {
                            Id = 13,
                            ImagePath = "img/Scenarios/gh-13.png",
                            Name = "Scenario 13"
                        },
                        new
                        {
                            Id = 14,
                            ImagePath = "img/Scenarios/gh-14.png",
                            Name = "Scenario 14"
                        },
                        new
                        {
                            Id = 15,
                            ImagePath = "img/Scenarios/gh-15.png",
                            Name = "Scenario 15"
                        },
                        new
                        {
                            Id = 16,
                            ImagePath = "img/Scenarios/gh-16.png",
                            Name = "Scenario 16"
                        },
                        new
                        {
                            Id = 17,
                            ImagePath = "img/Scenarios/gh-17.png",
                            Name = "Scenario 17"
                        },
                        new
                        {
                            Id = 18,
                            ImagePath = "img/Scenarios/gh-18.png",
                            Name = "Scenario 18"
                        },
                        new
                        {
                            Id = 19,
                            ImagePath = "img/Scenarios/gh-19.png",
                            Name = "Scenario 19"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "img/Scenarios/gh-2.png",
                            Name = "Scenario 2"
                        },
                        new
                        {
                            Id = 20,
                            ImagePath = "img/Scenarios/gh-20.png",
                            Name = "Scenario 20"
                        },
                        new
                        {
                            Id = 21,
                            ImagePath = "img/Scenarios/gh-21.png",
                            Name = "Scenario 21"
                        },
                        new
                        {
                            Id = 22,
                            ImagePath = "img/Scenarios/gh-22.png",
                            Name = "Scenario 22"
                        },
                        new
                        {
                            Id = 23,
                            ImagePath = "img/Scenarios/gh-23.png",
                            Name = "Scenario 23"
                        },
                        new
                        {
                            Id = 24,
                            ImagePath = "img/Scenarios/gh-24.png",
                            Name = "Scenario 24"
                        },
                        new
                        {
                            Id = 25,
                            ImagePath = "img/Scenarios/gh-25.png",
                            Name = "Scenario 25"
                        },
                        new
                        {
                            Id = 26,
                            ImagePath = "img/Scenarios/gh-26.png",
                            Name = "Scenario 26"
                        },
                        new
                        {
                            Id = 27,
                            ImagePath = "img/Scenarios/gh-27.png",
                            Name = "Scenario 27"
                        },
                        new
                        {
                            Id = 28,
                            ImagePath = "img/Scenarios/gh-28.png",
                            Name = "Scenario 28"
                        },
                        new
                        {
                            Id = 29,
                            ImagePath = "img/Scenarios/gh-29.png",
                            Name = "Scenario 29"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "img/Scenarios/gh-3.png",
                            Name = "Scenario 3"
                        },
                        new
                        {
                            Id = 30,
                            ImagePath = "img/Scenarios/gh-30.png",
                            Name = "Scenario 30"
                        },
                        new
                        {
                            Id = 31,
                            ImagePath = "img/Scenarios/gh-31.png",
                            Name = "Scenario 31"
                        },
                        new
                        {
                            Id = 32,
                            ImagePath = "img/Scenarios/gh-32.png",
                            Name = "Scenario 32"
                        },
                        new
                        {
                            Id = 33,
                            ImagePath = "img/Scenarios/gh-33.png",
                            Name = "Scenario 33"
                        },
                        new
                        {
                            Id = 34,
                            ImagePath = "img/Scenarios/gh-34.png",
                            Name = "Scenario 34"
                        },
                        new
                        {
                            Id = 35,
                            ImagePath = "img/Scenarios/gh-35-36.png",
                            Name = "Scenario 35"
                        },
                        new
                        {
                            Id = 36,
                            ImagePath = "img/Scenarios/gh-35-36.png",
                            Name = "Scenario 36"
                        },
                        new
                        {
                            Id = 37,
                            ImagePath = "img/Scenarios/gh-37.png",
                            Name = "Scenario 37"
                        },
                        new
                        {
                            Id = 38,
                            ImagePath = "img/Scenarios/gh-38.png",
                            Name = "Scenario 38"
                        },
                        new
                        {
                            Id = 39,
                            ImagePath = "img/Scenarios/gh-39.png",
                            Name = "Scenario 39"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "img/Scenarios/gh-4.png",
                            Name = "Scenario 4"
                        },
                        new
                        {
                            Id = 40,
                            ImagePath = "img/Scenarios/gh-40.png",
                            Name = "Scenario 40"
                        },
                        new
                        {
                            Id = 41,
                            ImagePath = "img/Scenarios/gh-41.png",
                            Name = "Scenario 41"
                        },
                        new
                        {
                            Id = 42,
                            ImagePath = "img/Scenarios/gh-42.png",
                            Name = "Scenario 42"
                        },
                        new
                        {
                            Id = 43,
                            ImagePath = "img/Scenarios/gh-43.png",
                            Name = "Scenario 43"
                        },
                        new
                        {
                            Id = 44,
                            ImagePath = "img/Scenarios/gh-44.png",
                            Name = "Scenario 44"
                        },
                        new
                        {
                            Id = 45,
                            ImagePath = "img/Scenarios/gh-45.png",
                            Name = "Scenario 45"
                        },
                        new
                        {
                            Id = 46,
                            ImagePath = "img/Scenarios/gh-46.png",
                            Name = "Scenario 46"
                        },
                        new
                        {
                            Id = 47,
                            ImagePath = "img/Scenarios/gh-47.png",
                            Name = "Scenario 47"
                        },
                        new
                        {
                            Id = 48,
                            ImagePath = "img/Scenarios/gh-48.png",
                            Name = "Scenario 48"
                        },
                        new
                        {
                            Id = 49,
                            ImagePath = "img/Scenarios/gh-49.png",
                            Name = "Scenario 49"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "img/Scenarios/gh-5.png",
                            Name = "Scenario 5"
                        },
                        new
                        {
                            Id = 50,
                            ImagePath = "img/Scenarios/gh-50.png",
                            Name = "Scenario 50"
                        },
                        new
                        {
                            Id = 51,
                            ImagePath = "img/Scenarios/gh-51.png",
                            Name = "Scenario 51"
                        },
                        new
                        {
                            Id = 52,
                            ImagePath = "img/Scenarios/gh-52.png",
                            Name = "Scenario 52"
                        },
                        new
                        {
                            Id = 53,
                            ImagePath = "img/Scenarios/gh-53.png",
                            Name = "Scenario 53"
                        },
                        new
                        {
                            Id = 54,
                            ImagePath = "img/Scenarios/gh-54.png",
                            Name = "Scenario 54"
                        },
                        new
                        {
                            Id = 55,
                            ImagePath = "img/Scenarios/gh-55.png",
                            Name = "Scenario 55"
                        },
                        new
                        {
                            Id = 56,
                            ImagePath = "img/Scenarios/gh-56.png",
                            Name = "Scenario 56"
                        },
                        new
                        {
                            Id = 57,
                            ImagePath = "img/Scenarios/gh-57.png",
                            Name = "Scenario 57"
                        },
                        new
                        {
                            Id = 58,
                            ImagePath = "img/Scenarios/gh-58.png",
                            Name = "Scenario 58"
                        },
                        new
                        {
                            Id = 59,
                            ImagePath = "img/Scenarios/gh-59.png",
                            Name = "Scenario 59"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "img/Scenarios/gh-6.png",
                            Name = "Scenario 6"
                        },
                        new
                        {
                            Id = 60,
                            ImagePath = "img/Scenarios/gh-60.png",
                            Name = "Scenario 60"
                        },
                        new
                        {
                            Id = 61,
                            ImagePath = "img/Scenarios/gh-61.png",
                            Name = "Scenario 61"
                        },
                        new
                        {
                            Id = 62,
                            ImagePath = "img/Scenarios/gh-62.png",
                            Name = "Scenario 62"
                        },
                        new
                        {
                            Id = 63,
                            ImagePath = "img/Scenarios/gh-63.png",
                            Name = "Scenario 63"
                        },
                        new
                        {
                            Id = 64,
                            ImagePath = "img/Scenarios/gh-64.png",
                            Name = "Scenario 64"
                        },
                        new
                        {
                            Id = 65,
                            ImagePath = "img/Scenarios/gh-65.png",
                            Name = "Scenario 65"
                        },
                        new
                        {
                            Id = 66,
                            ImagePath = "img/Scenarios/gh-66.png",
                            Name = "Scenario 66"
                        },
                        new
                        {
                            Id = 67,
                            ImagePath = "img/Scenarios/gh-67.png",
                            Name = "Scenario 67"
                        },
                        new
                        {
                            Id = 68,
                            ImagePath = "img/Scenarios/gh-68.png",
                            Name = "Scenario 68"
                        },
                        new
                        {
                            Id = 69,
                            ImagePath = "img/Scenarios/gh-69.png",
                            Name = "Scenario 69"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "img/Scenarios/gh-7.png",
                            Name = "Scenario 7"
                        },
                        new
                        {
                            Id = 70,
                            ImagePath = "img/Scenarios/gh-70.png",
                            Name = "Scenario 70"
                        },
                        new
                        {
                            Id = 71,
                            ImagePath = "img/Scenarios/gh-71.png",
                            Name = "Scenario 71"
                        },
                        new
                        {
                            Id = 72,
                            ImagePath = "img/Scenarios/gh-72.png",
                            Name = "Scenario 72"
                        },
                        new
                        {
                            Id = 73,
                            ImagePath = "img/Scenarios/gh-73.png",
                            Name = "Scenario 73"
                        },
                        new
                        {
                            Id = 74,
                            ImagePath = "img/Scenarios/gh-74.png",
                            Name = "Scenario 74"
                        },
                        new
                        {
                            Id = 75,
                            ImagePath = "img/Scenarios/gh-75.png",
                            Name = "Scenario 75"
                        },
                        new
                        {
                            Id = 76,
                            ImagePath = "img/Scenarios/gh-76.png",
                            Name = "Scenario 76"
                        },
                        new
                        {
                            Id = 77,
                            ImagePath = "img/Scenarios/gh-77.png",
                            Name = "Scenario 77"
                        },
                        new
                        {
                            Id = 78,
                            ImagePath = "img/Scenarios/gh-78.png",
                            Name = "Scenario 78"
                        },
                        new
                        {
                            Id = 79,
                            ImagePath = "img/Scenarios/gh-79.png",
                            Name = "Scenario 79"
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "img/Scenarios/gh-8.png",
                            Name = "Scenario 8"
                        },
                        new
                        {
                            Id = 80,
                            ImagePath = "img/Scenarios/gh-80.png",
                            Name = "Scenario 80"
                        },
                        new
                        {
                            Id = 81,
                            ImagePath = "img/Scenarios/gh-81.png",
                            Name = "Scenario 81"
                        },
                        new
                        {
                            Id = 82,
                            ImagePath = "img/Scenarios/gh-82.png",
                            Name = "Scenario 82"
                        },
                        new
                        {
                            Id = 83,
                            ImagePath = "img/Scenarios/gh-83.png",
                            Name = "Scenario 83"
                        },
                        new
                        {
                            Id = 84,
                            ImagePath = "img/Scenarios/gh-84.png",
                            Name = "Scenario 84"
                        },
                        new
                        {
                            Id = 85,
                            ImagePath = "img/Scenarios/gh-85.png",
                            Name = "Scenario 85"
                        },
                        new
                        {
                            Id = 86,
                            ImagePath = "img/Scenarios/gh-86.png",
                            Name = "Scenario 86"
                        },
                        new
                        {
                            Id = 87,
                            ImagePath = "img/Scenarios/gh-87.png",
                            Name = "Scenario 87"
                        },
                        new
                        {
                            Id = 88,
                            ImagePath = "img/Scenarios/gh-88.png",
                            Name = "Scenario 88"
                        },
                        new
                        {
                            Id = 89,
                            ImagePath = "img/Scenarios/gh-89.png",
                            Name = "Scenario 89"
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "img/Scenarios/gh-9.png",
                            Name = "Scenario 9"
                        },
                        new
                        {
                            Id = 90,
                            ImagePath = "img/Scenarios/gh-90.png",
                            Name = "Scenario 90"
                        },
                        new
                        {
                            Id = 91,
                            ImagePath = "img/Scenarios/gh-91.png",
                            Name = "Scenario 91"
                        },
                        new
                        {
                            Id = 92,
                            ImagePath = "img/Scenarios/gh-92.png",
                            Name = "Scenario 92"
                        },
                        new
                        {
                            Id = 93,
                            ImagePath = "img/Scenarios/gh-93.png",
                            Name = "Scenario 93"
                        },
                        new
                        {
                            Id = 94,
                            ImagePath = "img/Scenarios/gh-94.png",
                            Name = "Scenario 94"
                        },
                        new
                        {
                            Id = 95,
                            ImagePath = "img/Scenarios/gh-95.png",
                            Name = "Scenario 95"
                        });
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.CampaignScenario", b =>
                {
                    b.HasOne("GloomhavenCompanion.Data.Model.Campaign", "Campaign")
                        .WithMany("CampaignScenarios")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GloomhavenCompanion.Data.Model.Game", "Game")
                        .WithOne("CampaignScenario")
                        .HasForeignKey("GloomhavenCompanion.Data.Model.CampaignScenario", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GloomhavenCompanion.Data.Model.Scenario", "Scenario")
                        .WithMany("CampaignScenarios")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Game");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Card", b =>
                {
                    b.HasOne("GloomhavenCompanion.Data.Model.Deck", "Deck")
                        .WithMany("CardsList")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Effect", b =>
                {
                    b.HasOne("GloomhavenCompanion.Data.Model.Player", null)
                        .WithMany("Effects")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Game", b =>
                {
                    b.HasOne("GloomhavenCompanion.Data.Model.Deck", "MonsterDeck")
                        .WithMany()
                        .HasForeignKey("MonsterDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterDeck");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Player", b =>
                {
                    b.HasOne("GloomhavenCompanion.Data.Model.Campaign", "Campaign")
                        .WithMany("Players")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GloomhavenCompanion.Data.Model.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.PlayerGame", b =>
                {
                    b.HasOne("GloomhavenCompanion.Data.Model.Game", "Game")
                        .WithMany("PlayerGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GloomhavenCompanion.Data.Model.Player", "Player")
                        .WithMany("PlayerGames")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Round", b =>
                {
                    b.HasOne("GloomhavenCompanion.Data.Model.Game", null)
                        .WithMany("Rounds")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Scenario", b =>
                {
                    b.HasOne("GloomhavenCompanion.Data.Model.Campaign", null)
                        .WithMany("Scenarios")
                        .HasForeignKey("CampaignId");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Campaign", b =>
                {
                    b.Navigation("CampaignScenarios");

                    b.Navigation("Players");

                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Deck", b =>
                {
                    b.Navigation("CardsList");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Game", b =>
                {
                    b.Navigation("CampaignScenario")
                        .IsRequired();

                    b.Navigation("PlayerGames");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Player", b =>
                {
                    b.Navigation("Effects");

                    b.Navigation("PlayerGames");
                });

            modelBuilder.Entity("GloomhavenCompanion.Data.Model.Scenario", b =>
                {
                    b.Navigation("CampaignScenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
